# Azure pipeline
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr: 
  autoCancel: 'true'
  branches:
    include:
    - '*'
  paths:
    include:
    - '*' 

stages:
- stage: build
  displayName: 'Build .Net Core Samples'
  jobs:
  - template: .azurepipelines/ci.yml
- stage: buildnohttps
  dependsOn: []
  displayName: 'Build NoHttps .Net Core Samples'
  jobs:
  - template: .azurepipelines/ci.yml
    parameters:
      buildoption: '-p:NoHttps=true'
      agents: '@{ linux = "ubuntu-20.04" }'
- stage: solutions
  dependsOn: []
  displayName: 'Build Solutions'
  jobs:
  - template: .azurepipelines/sln.yml
- stage: testrelease
  dependsOn: []
  displayName: 'Test Core and SDK Release'
  jobs:
  - template: .azurepipelines/test.yml
    parameters:
      configuration: Release
      framework: net462
      agents: '@{ windows = "windows-2019" }'
      jobnamesuffix: net462
  - template: .azurepipelines/test.yml
    parameters:
      configuration: Release
      framework: net472
      agents: '@{ windows = "windows-2022" }'
      jobnamesuffix: net472
  - template: .azurepipelines/test.yml
    parameters:
      configuration: Release
      framework: net5.0
      agents: '@{ windows = "windows-2019" linux = "ubuntu-20.04" mac = "macOS-10.15" }'
      jobnamesuffix: net50
  - template: .azurepipelines/test.yml
    parameters:
      framework: netcoreapp2.1
      configuration: Release
  - template: .azurepipelines/test.yml
    parameters:
      configuration: Release
      framework: netcoreapp3.1
      jobnamesuffix: core3
  - template: .azurepipelines/test.yml
    parameters:
      configuration: Release
      agents: '@{ windows = "windows-2022" }'
      framework: net6.0
      jobnamesuffix: net60
- stage: testdebug
  dependsOn: []
  displayName: 'Test Core and SDK Debug'
  jobs:
  - template: .azurepipelines/test.yml
    parameters:
      framework: netcoreapp3.1
      configuration: Debug
  - template: .azurepipelines/test.yml
    parameters:
      configuration: Debug
      framework: net6.0
      jobnamesuffix: net60debug
- stage: coverage
  dependsOn: [testdebug,testrelease]
  displayName: 'Code Coverage'
  jobs:
  - template: .azurepipelines/testcc.yml
    parameters:
      configuration: Release
      poolImage: 'ubuntu-20.04'
      jobnamesuffix: netcore31
